x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "100m"

services:
  account-create:
    image: gcr.io/prysmaticlabs/prysm/validator:latest
    restart: "no"
    volumes:
      - ../src/yaml/validator-config.yaml:/config/config.yaml
      - ../src/keystore:/data/keystore
      - ../src/wallet:/var/lib/prysm/wallet
    # entrypoint: ["/bin/bash", "-c", "echo '1' | /bin/prysmctl validator wallet create --wallet-dir=/wallet --keymanager-kind=derived --wallet-password-file=/password.txt --accept-terms-of-use"]
    command:
      # [create new account]
      - wallet
      - create
      - --accept-terms-of-use
      - --wallet-dir=/var/lib/prysm/wallet
      - --keymanager-kind=direct
      - --wallet-password-file=/var/lib/prysm/wallet/password.txt
    <<: *logging

  wallet-import:
    image: gcr.io/prysmaticlabs/prysm/validator:latest
    restart: "no"
    depends_on:
      - account-create
    volumes:
      - ../src/yaml/validator-config.yaml:/config/config.yaml
      - ../src/keystore:/data/keystore
      - ../src/wallet:/var/lib/prysm/wallet
    command:
      # [create validator-key]
      - accounts
      - import
      - --wallet-dir=/var/lib/prysm/wallet
      - --wallet-password-file=/var/lib/prysm/wallet/password.txt
      - --keys-dir=/var/lib/prysm/wallet/direct/accounts/all-accounts.keystore.json
      - --account-password-file=/var/lib/prysm/wallet/password.txt
      - --accept-terms-of-use
    <<: *logging
    
